default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DSJ_DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DSJ_DB_PORT', '5432') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 5000

development:
  <<: *default
  database: DSJ_development
  username: <%= ENV['DSJ_DB_USERNAME'] %>
  password: <%= ENV['DSJ_DB_PASSWORD'] %>

test:
  <<: *default
  database: DSJ_test
  username: <%= ENV['DSJ_DB_USERNAME'] %>
  password: <%= ENV['DSJ_DB_PASSWORD'] %>
