
class CompleteForm < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Complete.new
    new(model, journey)
  end

  def params_key
    :complete
  end
end

