
class Over55Question1Form < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Over55Question1.new
    new(model, journey)
  end

  def params_key
    :over_55_question_1
  end
end

