
class Question2Form < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Question2.new
    new(model, journey)
  end

  def params_key
    :question_2
  end
end

