
class ReviewForm < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Review.new
    new(model, journey)
  end

  def params_key
    :review
  end
end

