
class Under35Question1Form < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Under35Question1.new
    new(model, journey)
  end

  def params_key
    :under_35_question_1
  end
end

