
class Under55Question3Form < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Under55Question3.new
    new(model, journey)
  end

  def params_key
    :under_55_question_3
  end
end

