
class Under25Question2Form < BaseForm

  def self.factory(journey)
    # Auto generated by DatashiftJourney - check this is really the Model this Form is managing
    model ||= Under25Question2.new
    new(model, journey)
  end

  def params_key
    :under_25_question_2
  end
end

